on:
  workflow_dispatch:
  
  
name: Upload Release Asset


jobs:
  build:
    name: Upload Release Asset
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Build project # This would actually build your project, using zip for an example artifact
        shell: cmd
        run: |
          echo ab > nmn.txt
          git config --global user.email github-actions@github.com
          git config --global user.name github-actions
          git pull
          git add -A
          git commit -m 'uploaded'
          git push

