on:
  workflow_dispatch:



jobs:
  build1:
    name: push changes
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        shell: pwsh 
        run: |
          echo ${{ env:TEMP }} 
          echo abc1 >> test.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push
  build2:
    needs: build1
    name: etts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - env:
          tempdir: ${{ runner.temp }} 
        run: |
          git pull
          echo abc2 >> test.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push
