on:
  workflow_dispatch:



jobs:
  build:
    name: push changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - env:
          tempdir: ${{ runner.temp }} 
        run: |
          node test.js
          date > generated.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push origin refs/heads/main
