on:
  workflow_dispatch:
  
  
name: Upload Release Asset

env: # Or as an environment variable
  user: ${{ secrets.USER }}
  key: ${{ secrets.KEY }}   
  

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build project # This would actually build your project, using zip for an example artifact
        run: |
          node test.js

