on:
  workflow_dispatch:
  
  
name: Upload Release Asset


jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:

        
        
      - uses: actions/checkout@v2
      - shell: bash
        run: |
          echo ab > nmn.txt
          git config --global user.email github-actions@github.com
          git config --global user.name github-actions
          git pull
          git add -A
          git commit -m 'uploaded'
          git push

